spring:
  datasource:
    password: IgfAH$@2018
    url: jdbc:mysql://localhost:3306/server-manager
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
